### ISSUE TITLE
Any progress ?

### ISSUE THREAD

**Issue by sokatra** [hschletz/Braintacle#1]
i don't see any updates on ocs-inventory fork? will braintacle be further developed in the future?
it might be better if you contribute your ideas to Project ocs-inventory? 
Kind regards

**Comment by hschletz** [comment]
The project is still alive. I use it frequently and it does what I need, thus there has not been much activity recently. Contributions are welcome, if only in the form of bug reports and feature requests. Also have a look at the git master branch -- not every change goes into a release immediately.
As for collaboration with OCSInventory-NG, I don't see much common ground. Braintacle is not a fork. The only shared code is the server component, heavily patched mostly to support different DBMS. The databases are incompatible. The user interface was written from scratch, with different workflows in mind. The agent, which Braintacle still relies on, is not part of the code. So it's really 2 applications designed for the same task, but doing things differently.

**Comment by sokatra** [comment]
Thanks for your fast response but i have 2 questions
1. are there any screenshot of the webinterface to see how braintacle look like?
2. are ocsinventory agent plugins compatible ?
kind regards

Sokatra

**Comment by hschletz** [comment]
There is no website yet and no screenshots. I'll see to creating a simple page using GitHub Pages.

Agent plugins can be supported in theory, but due to the lack of a generic plugin infrastructure the functionality has to be hardcoded into the application. Without this support, a plugin can be used with the agent, but the extra data will be ignored.

Coding support for every available plugin is not feasible, but single plugins can be supported by request. At this time, support for the [officepack](https://github.com/PluginsOCSInventory-NG/officepack) plugin is already included.

**Comment by hschletz** [comment]
Website with screenshots is here: https://hschletz.github.io/Braintacle/
