### ISSUE TITLE
How to access administration console

### ISSUE THREAD

**Issue by BlackSpartan** [hschletz/Braintacle#2]
Dear hschletz
May you please assist on how to access the administration console. 
1. when I type localhost/braintacle I am receiving a blank page. Here is the error from the log 

[Sun May 30 20:41:32.598137 2021] [php7:error] [pid 18211] [client 127.0.0.1:41616] PHP Fatal error:  Uncaught Error: Class 'Locale' not found in /usr/local/share/braintacle/module/Console/Module.php:65\nStack trace:\n#0 /usr/local/share/braintacle/vendor/laminas/laminas-eventmanager/src/EventManager.php(331): Console\\Module->onBootstrap(Object(Laminas\\Mvc\\MvcEvent))\n#1 /usr/local/share/braintacle/vendor/laminas/laminas-eventmanager/src/EventManager.php(180): Laminas\\EventManager\\EventManager->triggerListeners(Object(Laminas\\Mvc\\MvcEvent))\n#2 /usr/local/share/braintacle/vendor/laminas/laminas-mvc/src/Application.php(160): Laminas\\EventManager\\EventManager->triggerEvent(Object(Laminas\\Mvc\\MvcEvent))\n#3 /usr/local/share/braintacle/vendor/laminas/laminas-mvc/src/Application.php(272): Laminas\\Mvc\\Application->bootstrap(Array)\n#4 /usr/local/share/braintacle/module/Library/Application.php(39): Laminas\\Mvc\\Application::init(Array)\n#5 /usr/local/share/braintacle/public/index.php(28): Library\\Application::init('Console')\n#6 {main}\n  thrown in /usr/local/share/braintacle/module/Console/Module.php on line 65

2. Also when I typle localhost/braintacle-server I am getting a 403 status code, however I have granted permission to the file.
Forbidden

You don't have permission to access this resource.
Apache/2.4.29 (Ubuntu) Server at 127.0.0.1 Port 80

**Comment by hschletz** [comment]
1. The Locale class is provided by the intl extension. You have to enable the PHP extensions listed in README.md in your php.ini. Some extensions are provided by additional distro packages (php-intl, php-pgsql etc.)
2. This is expected. The braintacle-server URL provides the API to communicate with agents. This API uses POST requests only. You can test it with curl, for example:
````
# curl -X POST -v http://localhost/braintacle-server/
...
< HTTP/1.1 500 Internal Server Error
...
````
You will get a 500 error due to the empty request, but this is generated by the application, proving correct Apache setup. If you still get a 403 here, check the access controls in your Apache config. The default config uses `Require all granted` which should work unless overridden elsewhere.

3a9bd3a03e01c4a911ca57dd543a8faf1a1b1334 now returns a 405 error (Method not allowed) if not invoked via POST. This is more appropriate and helps distinguish between a server misconfiguration and an incorrect testing method.

**Comment by BlackSpartan** [comment]
Thank you so much.
